#spring:
##  config:
##    import: "optional:configserver:http://localhost:8088"
#  application:
#    name: authentication-service

server:
  port: 8082

spring:
  application:
    name: authentication-service
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/indpro-user
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#    registerWithEureka: true
#    fetchRegistry: true

entity-manager:
  packagesToScan: com.indpro.entity

